services:
  db:
    image: mongo
    container_name: ${DB_CONTAINER}
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - ${DB_VOLUME}:/data/db

  express:
    image: mongo-express
    container_name: ${EXPRESS_CONTAINER}
    restart: always
    ports:
      - ${EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASS}
      - ME_CONFIG_MONGODB_URL=mongodb://${DB_USER}:${DB_PASS}@${DB_CONTAINER}/
      - ME_CONFIG_MONGODB_SERVER=${DB_CONTAINER}
    depends_on:
      - db

  rest:
    build:
      context: .
    image: localhost:7002/plantcontrol-rest
    container_name: ${REST_CONTAINER}
    restart: always
    ports:
      - ${REST_PORT}:80
    environment:
      - CONNECTION_STRING=mongodb://${DB_USER}:${DB_PASS}@${DB_CONTAINER}/plantDB?authSource=admin&directConnection=true&ssl=false
    depends_on:
      - db

volumes:
  test-db:
    external: true
  prod-db:
    external: true
